# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:


# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)

import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

array = np.__version__

array


'1.23.5'

In [1]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])


In [ ]:
liste = [0.8, 0.6, 0.4]
my_array = np.array(liste)

my_array[0:]


array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])
def rando(a):
  my_array = np.random.random(a)
  if my_array[0] > 0.25 and my_array[0] < 1:
    return my_array
  else:
    return None

result = rando(10)
result






array([0.95725192, 0.97813608, 0.18480109, 0.57287477, 0.7917322 ,
       0.47097952, 0.69876122, 0.86887256, 0.06434999, 0.81296182])

In [ ]:
def rand(b):
  np.random.random(b)* 0.75 + 0.25
  return np.random.random(b) * 0.75 + 0.25

result = rand(10)
(result)

array([0.76992096, 0.5879928 , 0.915775  , 0.34327456, 0.87467166,
       0.33365181, 0.93926427, 0.29702527, 0.86572913, 0.91352521])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here
import numpy as np

np.empty(3)

#La fonction empty permet de créer un array (tableau) de deux, trois... dimensions avec des données aléatoires.

array([5.04647874e-310, 1.64080184e-306, 2.22550258e+252])

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
import numpy as np

np.zeros(6)


array([0., 0., 0., 0., 0., 0.])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.


In [ ]:
import numpy as np

np.empty(10, int)

array([4601777254466994984, 4600512537622590602, 4586059273902460704,
       4605120795110510752, 4607150347973645718, 4599157777676531788,
       4597136880793280404, 4605458131186995028, 4602304636472841372,
       4589714354251084952])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.


In [ ]:
import numpy as np

np.random.randint(0,7,50)




array([5, 6, 4, 0, 6, 5, 4, 6, 2, 2, 3, 2, 4, 5, 2, 6, 3, 4, 2, 1, 3, 3,
       3, 1, 6, 3, 5, 0, 3, 4, 2, 0, 0, 6, 1, 5, 5, 6, 6, 5, 0, 5, 1, 4,
       4, 6, 0, 5, 5, 3])

In [ ]:
import numpy as np
the_list = [0, 1, 2, 3, 4, 5, 6, 7]

np.random.choice(the_list, 50)

array([6, 2, 7, 4, 4, 5, 3, 0, 5, 5, 6, 2, 5, 6, 2, 3, 6, 2, 7, 7, 0, 4,
       2, 3, 3, 2, 5, 2, 3, 5, 3, 6, 6, 5, 5, 4, 4, 2, 3, 1, 0, 4, 5, 4,
       1, 4, 1, 0, 0, 3])